-- Supabase/PostgreSQL migration.
CREATE TABLE IF NOT EXISTS message_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT,
    channel TEXT NOT NULL,
    provider TEXT NOT NULL,
    recipient TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    provider_message_id TEXT,
    error TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at TIMESTAMPTZ,
    UNIQUE (venta_id, channel, recipient)
);

CREATE INDEX IF NOT EXISTS idx_message_deliveries_sale ON message_deliveries(venta_id);
CREATE INDEX IF NOT EXISTS idx_message_deliveries_status ON message_deliveries(status);
