CREATE TABLE IF NOT EXISTS venta_abonos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
    monto NUMERIC(14,2) NOT NULL CHECK (monto > 0),
    forma_pago TEXT NOT NULL DEFAULT 'Abono',
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    usuario_id BIGINT REFERENCES usuarios(id),
    nota TEXT
);
CREATE INDEX IF NOT EXISTS idx_venta_abonos_venta_fecha
    ON venta_abonos(venta_id, fecha, id);
