CREATE TABLE IF NOT EXISTS venta_devoluciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
    idempotency_key TEXT NOT NULL UNIQUE,
    motivo TEXT,
    usuario_id BIGINT REFERENCES usuarios(id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_venta_devoluciones_venta ON venta_devoluciones(venta_id);
