CREATE TABLE IF NOT EXISTS venta_devoluciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
    idempotency_key TEXT NOT NULL UNIQUE,
    motivo TEXT,
    usuario_id BIGINT REFERENCES usuarios(id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_venta_devoluciones_venta ON venta_devoluciones(venta_id);

CREATE TABLE IF NOT EXISTS venta_devolucion_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_id BIGINT NOT NULL REFERENCES venta_devoluciones(id) ON DELETE CASCADE,
    venta_item_id BIGINT NOT NULL REFERENCES venta_items(id) ON DELETE RESTRICT,
    producto_id BIGINT REFERENCES productos(id) ON DELETE RESTRICT,
    referencia TEXT,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0)
);
CREATE INDEX IF NOT EXISTS idx_venta_devolucion_items_devolucion
    ON venta_devolucion_items(devolucion_id);
