CREATE TABLE IF NOT EXISTS invoice_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL REFERENCES ventas(id) ON DELETE RESTRICT,
    channel TEXT NOT NULL CHECK (channel IN ('whatsapp', 'email')),
    provider TEXT NOT NULL,
    recipient TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'BLOCKED', 'RETRY_NOT_ALLOWED', 'ALREADY_SENT')),
    attempts INTEGER NOT NULL DEFAULT 1 CHECK (attempts > 0),
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invoice_deliveries_sale ON invoice_deliveries(venta_id);
CREATE INDEX IF NOT EXISTS idx_invoice_deliveries_status ON invoice_deliveries(status);
CREATE INDEX IF NOT EXISTS idx_invoice_deliveries_recipient ON invoice_deliveries(channel, recipient);
