(()=>{
'use strict';
const V2='/api/v2', API='/api';
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const money=v=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',minimumFractionDigits:0}).format(Number(v||0));
const dateOnly=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'—';
const msg=(m,t='success')=>window.toast?window.toast(m,t):console.log(m);
async function api(u,o={}){const r=await fetch(u,{credentials:'same-origin',...o}),b=await r.json().catch(()=>({}));if(!r.ok||b.ok===false)throw Error(b.error||`HTTP ${r.status}`);return b}
let sales=[],filter='',editing=null,items=[];
function admin(){return window.lumeonIsAdmin===true||String(window.currentUser?.role||'').toLowerCase()==='admin'}
async function auth(){try{const b=await api(`${V2}/auth/me`);if(b.authenticated){window.currentUser={user_id:b.user_id,username:b.username||String(b.user_id||''),role:String(b.role||'').toLowerCase()};window.lumeonIsAdmin=admin()}}catch(e){}$$('.admin-only-nav').forEach(e=>e.style.display=admin()?'':'none')}
function closeSale(){const m=$('#modal-venta');if(m)m.classList.remove('open');editing=null;items=[];window.editVentaId=null;window.ventaItems=[];showProductArea(true)}
function openSale(){const m=$('#modal-venta');if(!m)return msg('No se encontro el formulario de venta','error');m.classList.add('open')}
function showProductArea(v){const r=$('#vf-ref')?.parentElement,w=$('#vf-items-body')?.closest('.items-table-wrap'),s=$('#venta-summary');if(r)r.style.display=v?'':'none';if(w)w.style.display=v?'':'none';if(s)s.style.display=v?'':'none'}
async function clients(id=null){const b=await api(`${API}/clientes?q=`),a=Array.isArray(b)?b:(b.results||[]),s=$('#vf-cliente');if(!s)return;s.innerHTML='<option value="">-- Sin cliente --</option>'+a.map(c=>`<option value="${c.id}">${esc(c.nombre)}</option>`).join('');if(id!=null)s.value=String(id)}
function renderItems(){const b=$('#vf-items-body');if(!b)return;let t=0,g=0;b.innerHTML=items.map((x,i)=>{const q=+x.cantidad||0,p=+x.precio_venta||0,c=+x.precio_compra||0,l=q*p;t+=l;g+=q*(p-c);return `<tr><td>${esc(x.referencia)}</td><td>${esc(x.nombre)}</td><td>${q}</td><td>${money(c)}</td><td>${money(p)}</td><td>${money(l)}</td><td><button type="button" class="btn btn-danger btn-sm btn-icon" data-rm="${i}">X</button></td></tr>`}).join('');if($('#vs-sub'))$('#vs-sub').textContent=money(t);if($('#vs-total'))$('#vs-total').textContent=money(t);if($('#vs-gan'))$('#vs-gan').textContent=money(g);window.ventaItems=items;b.querySelectorAll('[data-rm]').forEach(x=>x.onclick=e=>{e.preventDefault();items.splice(+x.dataset.rm,1);renderItems()})}
async function addItem(){const ref=($('#vf-ref')?.value||'').trim(),q=+($('#vf-cant')?.value||1);if(!ref)return msg('Ingresa la referencia','error');if(!Number.isInteger(q)||q<=0)return msg('Cantidad invalida','error');try{const p=await api(`${API}/productos/buscar/${encodeURIComponent(ref)}`),x=p.result||p;if(!x?.id)throw Error('Producto no encontrado');const old=items.find(i=>i.referencia===x.referencia);if(old)old.cantidad+=q;else items.push({producto_id:+x.id,referencia:x.referencia,nombre:x.nombre,cantidad:q,precio_compra:+x.precio_compra||0,precio_venta:+x.precio_venta||0});renderItems();$('#vf-ref').value='';$('#vf-cant').value='1'}catch(e){msg(e.message,'error')}}
async function loadSales(){const b=$('#tbl-ventas tbody');if(!b)return;try{const d=await api(`${V2}/sales?q=${encodeURIComponent($('#venta-search')?.value||'')}`);sales=d.results||[];renderSales()}catch(e){b.innerHTML=`<tr><td colspan="9" class="empty"><div class="empty-title">Error al cargar ventas</div><div class="empty-text">${esc(e.message)}</div></td></tr>`}}
function renderSales(){const b=$('#tbl-ventas tbody');if(!b)return;const q=($('#venta-search')?.value||'').trim().toLowerCase(),f=filter.toLowerCase(),d=sales.filter(v=>{const text=[v.numero_factura,v.cliente_nombre,v.cliente_email,v.cliente_telefono].filter(Boolean).join(' ').toLowerCase(),st=String(v.estado||'Pendiente').toLowerCase(),ps=String(v.estado_pago||'').toLowerCase();return(!f||(f==='abonado'?ps==='abonado':st===f))&&(!q||text.includes(q))});if(!d.length){b.innerHTML='<tr><td colspan="9" class="empty"><div class="empty-title">Sin ventas</div><div class="empty-text">No hay ventas para este filtro.</div></td></tr>';return}b.innerHTML=d.map(v=>{const a=admin(),st=String(v.estado||'Pendiente'),bal=+v.saldo_pendiente||0,shown=v.estado_pago||st;return `<tr><td class="td-mono">${esc(v.numero_factura||'—')}</td><td>${esc(v.cliente_nombre||'—')}</td><td>${esc(v.ciclo||'—')}</td><td>${dateOnly(v.fecha)}</td><td>${esc(v.forma_pago||'Contado')}</td><td class="td-mono">${money(v.total)}</td><td class="td-mono">${money(v.ganancia)}</td><td>${typeof window.badgeEstado==='function'?window.badgeEstado(shown):esc(shown)}</td><td class="sales-actions">${a?`<button type="button" class="btn btn-ghost btn-sm btn-icon" data-x="e" data-id="${v.id}">EDIT</button>${st.toLowerCase()!=='pagado'&&st.toLowerCase()!=='cancelado'?`<button type="button" class="btn btn-success btn-sm" data-x="p" data-id="${v.id}">PAGADA</button>`:''}${bal>0&&st.toLowerCase()!=='cancelado'?`<button type="button" class="btn btn-gold btn-sm" data-x="a" data-id="${v.id}">ABONO</button>`:''}${st.toLowerCase()==='pendiente'?`<button type="button" class="btn btn-ghost btn-sm btn-icon" data-x="c" data-id="${v.id}">X</button>`:''}<button type="button" class="btn btn-danger btn-sm btn-icon" data-x="d" data-id="${v.id}" data-i="${esc(v.numero_factura||'')}">DEL</button>`:'—'}</td></tr>`}).join('');b.querySelectorAll('[data-x]').forEach(x=>x.onclick=e=>{e.preventDefault();e.stopPropagation();const id=+x.dataset.id;switch(x.dataset.x){case'e':editSale(id);break;case'p':statusSale(id,'Pagado');break;case'a':payment(id);break;case'c':statusSale(id,'Cancelado');break;case'd':delSale(id,x.dataset.i||'')}})}
function bindFilters(){const s=$('#venta-search');if(s)s.oninput=renderSales;const tabs=$$('#ventas-tabs .tab'),states=['','Pendiente','Abonado','Pagado','Cancelado'];tabs.forEach((t,i)=>{t.type='button';t.onclick=e=>{e.preventDefault();e.stopPropagation();filter=states[i]||'';tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');renderSales()}})}
async function editSale(id){try{const d=await api(`${V2}/sales/${id}`),v=d.venta||{};editing=+id;$('#mv-title')&&($('#mv-title').textContent='Editar Venta');$('#btn-save-venta')&&($('#btn-save-venta').textContent='Guardar cambios');const set=(q,v)=>{if($(q))$(q).value=v??''};set('#vf-num',v.numero_factura);set('#vf-fecha',v.fecha?String(v.fecha).slice(0,10):'');set('#vf-ciclo',v.ciclo);set('#vf-ciclo-inicio',v.fecha_inicio_ciclo);set('#vf-ciclo-fin',v.fecha_fin_ciclo);set('#vf-pago',v.forma_pago||'Contado');set('#vf-estado',v.estado||'Pendiente');set('#vf-email',v.cliente_email);set('#vf-tel',v.cliente_telefono);set('#vf-notas',v.notas);await clients(v.cliente_id);items=d.items||[];renderItems();showProductArea(false);openSale()}catch(e){msg(e.message,'error')}}
async function saveSale(){const c=$('#vf-cliente'),base={numero_factura:$('#vf-num')?.value.trim()||'',cliente_id:c?.value||null,cliente_nombre:c?.selectedOptions?.[0]?.text||'',cliente_email:$('#vf-email')?.value.trim()||'',cliente_telefono:$('#vf-tel')?.value.trim()||'',fecha:$('#vf-fecha')?.value||null,forma_pago:$('#vf-pago')?.value||'Contado',estado:$('#vf-estado')?.value||'Pendiente',notas:$('#vf-notas')?.value||'',ciclo:$('#vf-ciclo')?.value.trim()||'',fecha_inicio_ciclo:$('#vf-ciclo-inicio')?.value||null,fecha_fin_ciclo:$('#vf-ciclo-fin')?.value||null};try{if(editing!=null){await api(`${V2}/sales/${editing}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(base)});msg('Venta actualizada correctamente')}else{if(!items.length)throw Error('Agrega al menos un producto');const total=items.reduce((s,x)=>s+(+x.cantidad||0)*(+x.precio_venta||0),0);let initial=0;if(base.forma_pago==='Abono'){initial=+($('#vf-abono-inicial')?.value||0);if(!Number.isFinite(initial)||initial<=0||initial>total)throw Error('Abono inicial invalido')}await api(`${V2}/sales`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...base,items,initial_payment:initial})});msg('Venta registrada correctamente')}closeSale();await loadSales()}catch(e){msg(e.message,'error')}}
async function statusSale(id,state){try{await api(`${V2}/sales/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({estado:state})});msg(state==='Pagado'?'Venta marcada como pagada':'Venta cancelada');await loadSales()}catch(e){msg(e.message,'error')}}
async function delSale(id,invoice){if(!confirm(`Eliminar venta ${invoice}?`))return;try{await api(`${V2}/sales/${id}`,{method:'DELETE'});msg('Venta eliminada');await loadSales()}catch(e){msg(e.message,'error')}}
async function payment(id){const amount=+String(prompt('Valor del abono:')||'').replace(',','.');if(!Number.isFinite(amount)||amount<=0)return msg('Monto invalido','error');try{const d=await api(`${V2}/sales/${id}/payments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({monto:amount,forma_pago:'Abono'})}),v=d.venta||{};msg(+v.saldo_pendiente>0?`Abono registrado. Saldo: ${money(v.saldo_pendiente)}`:'Abono registrado. Venta pagada.');await loadSales()}catch(e){msg(e.message,'error')}}
async function openNewSale(){editing=null;items=[];$('#mv-title')&&($('#mv-title').textContent='Nueva Venta');$('#btn-save-venta')&&($('#btn-save-venta').textContent='Registrar Venta');$('#vf-num')&&($('#vf-num').value=`FAC-${Date.now()}`);$('#vf-fecha')&&($('#vf-fecha').value=new Date().toISOString().slice(0,10));$('#vf-pago')&&($('#vf-pago').value='Contado');$('#vf-estado')&&($('#vf-estado').value='Pendiente');$('#vf-abono-inicial')&&($('#vf-abono-inicial').value='');showProductArea(true);try{await clients(null);renderItems();openSale()}catch(e){msg(e.message,'error')}}
function bindModal(){const m=$('#modal-venta');if(!m)return;const save=$('#btn-save-venta');if(save)save.onclick=e=>{e.preventDefault();e.stopPropagation();saveSale()};m.querySelectorAll('button').forEach(b=>{if(b===save)return;const t=(b.textContent||'').trim().toLowerCase();if(t==='cancelar'||t==='x'||t==='×'||String(b.className).includes('modal-close'))b.onclick=e=>{e.preventDefault();e.stopPropagation();closeSale()}});const add=$('#vf-ref')?.parentElement?.querySelector('button');if(add)add.onclick=e=>{e.preventDefault();e.stopPropagation();addItem()};$('#vf-ref')&&($('#vf-ref').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addItem()}})}
function nav(){const map={dashboard:'dashboard',inventario:'inventario',ventas:'ventas',clientes:'clientes',ciclos:'ciclos',devoluciones:'devoluciones',registros:'admin-logs'};$$('#sidebar .nav-item').forEach(n=>n.onclick=e=>{e.preventDefault();e.stopPropagation();const p=map[n.textContent.trim().toLowerCase()];if(!p)return;$$('.page').forEach(x=>x.classList.remove('active'));$(`#page-${p}`)?.classList.add('active');window.currentPage=p;if(p==='ventas')loadSales();else if(p==='dashboard')window.loadDashboard?.();else if(p==='inventario')window.loadInventario?.();else if(p==='clientes')window.loadClientes?.();else if(p==='ciclos')window.loadCiclos?.();else if(p==='devoluciones')window.loadDevoluciones?.();else if(p==='admin-logs')window.loadAdminLogs?.()});window.goto=p=>{const n=$$('#sidebar .nav-item').find(x=>map[x.textContent.trim().toLowerCase()]===p);if(n)n.click()}}
function start(){const top=$('#topbar-action');if(top){top.style.display='none';top.type='button';top.onclick=e=>{e.preventDefault();e.stopPropagation();openNewSale()}}$$('#page-ventas .page-header button').forEach(b=>{if((b.textContent||'').toLowerCase().includes('nueva venta'))b.remove()});window.openModalVenta=openNewSale;window.saveVenta=saveSale;window.openSaleForEdit=editSale;window.editarVenta=editSale;window.markSalePaid=id=>statusSale(id,'Pagado');window.marcarPagada=window.markSalePaid;window.cancelSale=id=>statusSale(id,'Cancelado');window.cambiarEstado=window.cancelSale;window.deleteSaleFromUi=delSale;window.eliminarVenta=delSale;window.addSalePayment=payment;window.registrarAbono=payment;window.addSaleItem=addItem;window.removeSaleItem=i=>{items.splice(+i,1);renderItems()};window.loadVentas=loadSales;bindModal();bindFilters();nav();auth();if($('#page-ventas')?.classList.contains('active'))loadSales()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
