(() => {
'use strict';
const API='/api', V2='/api/v2';
let sales=[], salesFilter='', editingId=null, saleItems=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const safe=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const money=v=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',minimumFractionDigits:0}).format(Number(v||0));
const dateOnly=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'—';
const toast=(m,t='success')=>typeof window.toast==='function'?window.toast(m,t):console.log(m);
async function api(url,o={}){const r=await fetch(url,{credentials:'same-origin',...o});const b=await r.json().catch(()=>({}));if(!r.ok||b.ok===false)throw new Error(b.error||`HTTP ${r.status}`);return b;}
function isAdmin(){return window.lumeonIsAdmin===true||String(window.currentUser?.role||'').toLowerCase()==='admin';}
async function syncAuth(){try{const b=await api(`${V2}/auth/me`);if(b.authenticated){window.currentUser={id:b.user_id,user_id:b.user_id,username:b.username||b.user?.username||'',role:String(b.role||b.user?.role||'').toLowerCase()};window.lumeonIsAdmin=window.currentUser.role==='admin';}}catch(e){}showAdminNav();}
function showAdminNav(){$$('.admin-only-nav').forEach(e=>e.style.display=isAdmin()?'':'none');}
function navigate(page){const target=$(`#page-${page}`);if(!target)return;$$('.page').forEach(p=>p.classList.remove('active'));target.classList.add('active');$$('#sidebar .nav-item').forEach(n=>n.classList.remove('active'));const map={dashboard:'dashboard',inventario:'inventario',ventas:'ventas',clientes:'clientes',ciclos:'ciclos',devoluciones:'devoluciones',registros:'admin-logs'};$$('#sidebar .nav-item').forEach(n=>{if(map[n.textContent.trim().toLowerCase()]===page)n.classList.add('active');});if(page==='admin-logs')$('#nav-registros')?.classList.add('active');const titles={dashboard:'Dashboard',inventario:'Inventario',ventas:'Ventas',clientes:'Clientes',ciclos:'Ciclos',devoluciones:'Devoluciones','admin-logs':'Registros'};if($('#topbar-title'))$('#topbar-title').textContent=titles[page]||'Lumeon';window.currentPage=page;$('#content')&&($('#content').scrollTop=0);if(page==='ventas')loadSales();else if(page==='ciclos')loadCycles();else if(page==='admin-logs')loadLogs();else if(page==='dashboard')window.loadDashboard?.();else if(page==='inventario')window.loadInventario?.();else if(page==='clientes')window.loadClientes?.();else if(page==='devoluciones')window.loadDevoluciones?.();window.closeMobileMenu?.();}
function bindNav(){$$('#sidebar .nav-item').forEach(item=>item.onclick=e=>{e.preventDefault();const t=item.textContent.trim().toLowerCase();const map={dashboard:'dashboard',inventario:'inventario',ventas:'ventas',clientes:'clientes',ciclos:'ciclos',devoluciones:'devoluciones',registros:'admin-logs'};if(map[t])navigate(map[t]);});window.goto=navigate;}
async function loadSales(){const tbody=$('#tbl-ventas tbody');if(!tbody)return;try{let b;try{b=await api(`${V2}/sales?q=${encodeURIComponent($('#venta-search')?.value||'')}`);}catch(e){b=await api(`${API}/ventas?q=${encodeURIComponent($('#venta-search')?.value||'')}`);sales=Array.isArray(b)?b:(b.results||[]);renderSales();return;}sales=b.results||[];renderSales();}catch(e){sales=[];renderSales();toast(`Ventas: ${e.message}`,'error');}}
function renderSales(){const body=$('#tbl-ventas tbody');if(!body)return;const q=($('#venta-search')?.value||'').trim().toLowerCase();const rows=sales.filter(v=>{const text=[v.numero_factura,v.cliente_nombre,v.cliente_email,v.cliente_telefono].filter(Boolean).join(' ').toLowerCase();const st=String(v.estado||'').toLowerCase(),ps=String(v.estado_pago||'').toLowerCase();return(!q||text.includes(q))&&(!salesFilter||(salesFilter==='Abonado'?ps==='abonado':st===salesFilter.toLowerCase()));});body.innerHTML=rows.length?rows.map(v=>{const a=isAdmin(),st=String(v.estado||'Pendiente'),bal=Number(v.saldo_pendiente||0),shown=v.estado_pago||st;const act=[];if(a)act.push(`<button class="btn btn-ghost btn-sm btn-icon" data-edit="${v.id}" title="Editar">✎</button>`);if(a&&st.toLowerCase()!=='pagado'&&st.toLowerCase()!=='cancelado')act.push(`<button class="btn btn-success btn-sm" data-paid="${v.id}">Pagada</button>`);if(a&&bal>0&&st.toLowerCase()!=='cancelado')act.push(`<button class="btn btn-gold btn-sm" data-pay="${v.id}" data-invoice="${safe(v.numero_factura)}">Abono</button>`);if(a&&st.toLowerCase()==='pendiente')act.push(`<button class="btn btn-ghost btn-sm btn-icon" data-cancel="${v.id}">✕</button>`);if(a)act.push(`<button class="btn btn-danger btn-sm btn-icon" data-delete="${v.id}" data-invoice="${safe(v.numero_factura)}">🗑</button>`);return `<tr><td class="td-mono">${safe(v.numero_factura||'—')}</td><td>${safe(v.cliente_nombre||'—')}</td><td><span class="badge badge-blue">${safe(v.ciclo||'—')}</span></td><td>${dateOnly(v.fecha)}</td><td>${safe(v.forma_pago||'Contado')}</td><td class="td-mono">${money(v.total)}</td><td class="td-mono" style="color:var(--sage)">${money(v.ganancia)}</td><td>${typeof window.badgeEstado==='function'?window.badgeEstado(shown):safe(shown)}</td><td class="sales-actions">${act.join('')||'—'}</td></tr>`;}).join(''):`<tr><td colspan="9" class="empty"><div class="empty-title">Sin ventas</div><div class="empty-text">No hay ventas para este filtro.</div></td></tr>`;body.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editSale(+b.dataset.edit));body.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>changeStatus(+b.dataset.paid,'Pagado'));body.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>paymentPrompt(+b.dataset.pay,b.dataset.invoice||''));body.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>changeStatus(+b.dataset.cancel,'Cancelado'));body.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteSale(+b.dataset.delete,b.dataset.invoice||''));}
function bindSales(){const search=$('#venta-search');if(search)search.oninput=renderSales;$('#ventas-tabs')?.querySelectorAll('.tab').forEach((b,i)=>{const states=['','Pendiente','Abonado','Pagado','Cancelado'];b.onclick=()=>{salesFilter=states[i]||'';$('#ventas-tabs').querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSales();};});}
async function loadClients(id){const b=await api(`${V2}/clientes?q=&limit=200`);const s=$('#vf-cliente');if(!s)return;s.innerHTML='<option value="">-- Sin cliente --</option>'+(b.results||[]).map(c=>`<option value="${c.id}">${safe(c.nombre)}</option>`).join('');if(id!=null)s.value=String(id);}
function renderItems(){const body=$('#vf-items-body');if(!body)return;let total=0,gain=0;body.innerHTML=saleItems.map((i,n)=>{const q=+i.cantidad||0,p=+i.precio_compra||0,s=+i.precio_venta||0,line=q*s;total+=line;gain+=q*(s-p);return `<tr><td>${safe(i.referencia)}</td><td>${safe(i.nombre)}</td><td>${q}</td><td>${money(p)}</td><td>${money(s)}</td><td>${money(line)}</td><td><button class="btn btn-danger btn-sm btn-icon" data-rm="${n}">✕</button></td></tr>`;}).join('');if($('#vs-sub'))$('#vs-sub').textContent=money(total);if($('#vs-total'))$('#vs-total').textContent=money(total);if($('#vs-gan'))$('#vs-gan').textContent=money(gain);body.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{saleItems.splice(+b.dataset.rm,1);renderItems();});}
async function addItem(){const ref=$('#vf-ref')?.value.trim(),qty=+($('#vf-cant')?.value||1);if(!ref)return toast('Ingresa la referencia','error');try{const p=await api(`${API}/productos/buscar/${encodeURIComponent(ref)}`);if(!p.id)throw new Error('Producto no encontrado');const i=saleItems.findIndex(x=>x.referencia===p.referencia);if(i>=0)saleItems[i].cantidad+=qty;else saleItems.push({producto_id:+p.id,referencia:p.referencia,nombre:p.nombre,cantidad:qty,precio_compra:+p.precio_compra||0,precio_venta:+p.precio_venta||0});renderItems();$('#vf-ref').value='';$('#vf-cant').value='1';}catch(e){toast(e.message,'error');}}
function openModalSafe(){if(typeof window.openModal==='function')window.openModal('modal-venta');else $('#modal-venta')?.classList.add('open');}
function closeModalSafe(){if(typeof window.closeModal==='function')window.closeModal('modal-venta');else $('#modal-venta')?.classList.remove('open');editingId=null;window.editVentaId=null;}
async function openSale(){try{editingId=null;saleItems=[];window.ventaItems=[];$('#mv-title')&&($('#mv-title').textContent='Nueva Venta');$('#btn-save-venta')&&($('#btn-save-venta').textContent='Registrar Venta');if($('#vf-num'))$('#vf-num').value=`FAC-${Date.now()}`;if($('#vf-fecha'))$('#vf-fecha').value=new Date().toISOString().slice(0,10);if($('#vf-pago'))$('#vf-pago').value='Contado';if($('#vf-estado'))$('#vf-estado').value='Pendiente';if($('#vf-abono-inicial'))$('#vf-abono-inicial').value='';await loadClients(null);renderItems();openModalSafe();}catch(e){toast(`No se pudo abrir venta: ${e.message}`,'error');}}
async function editSale(id){try{const d=await api(`${V2}/sales/${id}`),s=d.venta||{};editingId=id;window.editVentaId=id;await loadClients(s.cliente_id);const set=(id,v)=>{if($(id))$(id).value=v??''};set('#vf-num',s.numero_factura);set('#vf-fecha',s.fecha?String(s.fecha).slice(0,10):'');set('#vf-ciclo',s.ciclo);set('#vf-ciclo-inicio',s.fecha_inicio_ciclo);set('#vf-ciclo-fin',s.fecha_fin_ciclo);set('#vf-pago',s.forma_pago||'Contado');set('#vf-email',s.cliente_email);set('#vf-tel',s.cliente_telefono);set('#vf-notas',s.notas);set('#vf-estado',s.estado||'Pendiente');saleItems=d.items||[];window.ventaItems=saleItems;renderItems();openModalSafe();}catch(e){toast(e.message,'error');}}
async function saveSale(){const sel=$('#vf-cliente');const base={numero_factura:$('#vf-num')?.value.trim(),cliente_id:sel?.value||null,cliente_nombre:sel?.selectedOptions?.[0]?.text||'',cliente_email:$('#vf-email')?.value.trim()||'',cliente_telefono:$('#vf-tel')?.value.trim()||'',fecha:$('#vf-fecha')?.value||null,forma_pago:$('#vf-pago')?.value||'Contado',estado:$('#vf-estado')?.value||'Pendiente',notas:$('#vf-notas')?.value||'',ciclo:$('#vf-ciclo')?.value.trim()||'',fecha_inicio_ciclo:$('#vf-ciclo-inicio')?.value||null,fecha_fin_ciclo:$('#vf-ciclo-fin')?.value||null};try{if(editingId!=null){await api(`${V2}/sales/${editingId}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...base,items:saleItems})});toast('Venta actualizada');}else{if(!saleItems.length)return toast('Agrega al menos un producto','error');const total=saleItems.reduce((s,i)=>s+(+i.cantidad||0)*(+i.precio_venta||0),0);const init=base.forma_pago==='Abono'?+(($('#vf-abono-inicial')?.value||0)):0;if(base.forma_pago==='Abono'&&(!Number.isFinite(init)||init<=0||init>total))return toast('Abono inicial inválido','error');await api(`${V2}/sales`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...base,initial_payment:init,items:saleItems})});toast(base.forma_pago==='Abono'?'Venta registrada con abono':'Venta registrada');}closeModalSafe();await loadSales();window.loadDashboard?.();window.loadInventario?.();loadCycles();}catch(e){toast(e.message,'error');}}
async function changeStatus(id,state){try{await api(`${V2}/sales/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({estado:state})});toast(state==='Pagado'?'Venta marcada como pagada':`Venta ${state}`);await loadSales();window.loadDashboard?.();loadCycles();}catch(e){toast(e.message,'error');}}
async function deleteSale(id,invoice){if(!confirm(`¿Eliminar la venta ${invoice}?`))return;try{await api(`${V2}/sales/${id}`,{method:'DELETE'});toast('Venta eliminada');await loadSales();window.loadDashboard?.();window.loadInventario?.();loadCycles();}catch(e){toast(e.message,'error');}}
async function paymentPrompt(id,invoice){const amount=+(prompt(`Valor del abono para ${invoice}:`)||0);if(!Number.isFinite(amount)||amount<=0)return toast('Monto inválido','error');try{const b=await api(`${V2}/sales/${id}/payments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({monto:amount,forma_pago:'Abono'})});toast(b.venta?.saldo_pendiente>0?`Abono registrado. Saldo: ${money(b.venta.saldo_pendiente)}`:'Abono registrado. Venta pagada.');await loadSales();loadCycles();}catch(e){toast(e.message,'error');}}
async function loadCycles(){const box=$('#ciclos-container');if(!box)return;try{const raw=await api(`${API}/ciclos`),list=Array.isArray(raw)?raw:(raw.results||[]);if(!list.length){box.innerHTML='<div class="empty"><div class="empty-title">Sin ciclos</div><div class="empty-text">No hay ciclos registrados.</div></div>';return;}const data=await Promise.all(list.map(async c=>{try{return await api(`${API}/ciclos/${encodeURIComponent(c)}/resumen`)}catch(e){return{ciclo:c,total:0,ganancia:0,num_ventas:0,ventas:[]}}}));box.innerHTML=data.map(s=>`<div class="card" style="margin-bottom:12px"><div class="card-header"><div><div class="card-title">Ciclo ${safe(s.ciclo)}</div><div class="card-subtitle">${s.num_ventas||0} ventas</div></div><strong>${money(s.total)}</strong></div><div style="font-size:11px;color:var(--ink3)">Ganancia: ${money(s.ganancia)}</div></div>`).join('');}catch(e){box.innerHTML=`<div class="empty"><div class="empty-title">Error al cargar ciclos</div><div class="empty-text">${safe(e.message)}</div></div>`;}}
async function loadLogs(){const box=$('#admin-logs-list');if(!box)return;try{const b=await api(`${V2}/admin/logs?limit=200`),rows=b.results||[];box.innerHTML=rows.length?rows.map(r=>`<div class="admin-log-card"><div class="admin-log-head"><strong>${safe(r.action)}</strong><span>${safe(r.username||'sistema')}</span><span>${safe(r.created_at||'')}</span></div><div class="admin-log-entity">${safe(r.entity_type||'sistema')} #${safe(r.entity_id||'—')}</div><div class="admin-log-meta">${safe(r.metadata||'')}</div></div>`).join(''):'<div class="empty"><div class="empty-title">Sin registros</div></div>';}catch(e){box.innerHTML=`<div class="empty"><div class="empty-title">Error al cargar registros</div><div class="empty-text">${safe(e.message)}</div></div>`;}}
function bind(){bindNav();bindSales();$('#btn-save-venta')&&( $('#btn-save-venta').onclick=saveSale);const close=$$('#modal-venta .btn-close, #modal-venta .modal-footer .btn-secondary');close.forEach(b=>b.onclick=e=>{e.preventDefault();closeModalSafe()});const add=$('#vf-ref')?.parentElement?.querySelector('button');if(add)add.onclick=addItem;window.openModalVenta=openSale;window.editarVenta=editSale;window.saveVenta=saveSale;window.marcarPagada=id=>changeStatus(id,'Pagado');window.cambiarEstado=changeStatus;window.eliminarVenta=deleteSale;window.registrarAbono=paymentPrompt;window.loadVentas=loadSales;window.renderVentas=renderSales;window.filterVentas=(b,s)=>{salesFilter=s||'';$('#ventas-tabs')?.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b?.classList.add('active');renderSales()};window.loadCiclos=loadCycles;window.loadAdminLogs=loadLogs;syncAuth();if($('#page-ventas')?.classList.contains('active'))loadSales();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
